version: 2
updates:
  - package-ecosystem: npm
    directories:
      - '/javascript'
      - '/typescript'
    schedule:
      interval: weekly
    open-pull-requests-limit: 99
    assignees:
      - ffflorian
    versioning-strategy: increase
    groups:
      babel:
        patterns:
          - '@babel/*'
      typescript-eslint:
        patterns:
          - '@typescript-eslint/*'
    ignore:
      - dependency-name: '@types/node'
        versions:
          - '> 26'
      - dependency-name: 'eslint'
        versions:
          - '> 8'
    cooldown:
      default-days: 5
      exclude:
        - '@ffflorian/*'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 99
    assignees:
      - ffflorian
    cooldown:
      default-days: 5
      exclude:
        - 'ffflorian/*'
