version: 2
updates:
- package-ecosystem: npm
  directory: "/typescript"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - ffflorian
  versioning-strategy: increase
  ignore:
  - dependency-name: "@types/node"
    versions:
    - "> 13.1.6"
    - "< 14"
  - dependency-name: "@types/node"
    versions:
    - ">= 13.a"
    - "< 14"
- package-ecosystem: npm
  directory: "/javascript"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - ffflorian
  versioning-strategy: increase
