sudo: false

language: node_js
node_js:
  - "8"

addons:
  apt:
    packages:
      - python3

notifications:
  email: false

cache:
  directories:
    - $HOME/.npm
    - $HOME/.cargo
    - $HOME/.rustup
    - javascript/node_modules

before_install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - source "$HOME/.cargo/env"

install:
  - (cd javascript && yarn)

script:
  - ./test_all.sh
