# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: node_js
node_js:
  - "8"

addons:
  apt:
    packages:
      - python3

cache:
  directories:
    - $HOME/.npm
    - $HOME/.cargo
    - javascript/node_modules

before_install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - source "$HOME/.cargo/env"

install:
  - (cd javascript && yarn)

# http://docs.travis-ci.com/user/pull-requests/
script:
  - ./test_all.sh
