name: Bash tests

permissions: {}

on:
  push:
    paths:
      - 'bash/**'
      - '.github/workflows/bash.yml'

jobs:
  test_bash:
    permissions:
      contents: read
    name: Test Bash
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - name: Install bats
        run: |
          sudo apt install bats
      - name: Run the tests
        working-directory: bash
        run: |
          ../bin/test_all.sh "*.sh" "bats *_test.sh"
