name: Go tests

permissions: {}

on:
  push:
    paths:
      - 'go/**'
      - '.github/workflows/go.yml'

jobs:
  test_go:
    permissions:
      contents: read
    name: Test Go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Set up latest Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e
        with:
          go-version: stable
      - name: Run the tests
        working-directory: go
        run: |
          ../bin/test_all.sh "*_test.go" "go test"
