name: Go tests

permissions: {}

on:
  push:
    paths:
      - 'go/**'
      - '.github/workflows/go.yml'

jobs:
  test_go:
    permissions:
      contents: read
    name: Test Go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - name: Set up latest Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16
        with:
          go-version: stable
      - name: Run the tests
        working-directory: go
        run: |
          ../bin/test_all.sh "*_test.go" "go test"
