name: Python tests

permissions: {}

on:
  push:
    paths:
      - 'python/**'
      - '.github/workflows/python.yml'

jobs:
  test_python:
    permissions:
      contents: read
    name: Test Python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - name: Set up Python 3.x
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          pip install pytest pytest-cov
      - name: Run the tests
        working-directory: python
        run: |
          ../bin/test_all.sh "*_test.py" "pytest *_test.py"
