name: Python tests

permissions: {}

on:
  push:
    paths:
      - 'python/**'
      - '.github/workflows/python.yml'

jobs:
  test_python:
    permissions:
      contents: read
    name: Test Python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - name: Set up Python 3.x
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          pip install pytest pytest-cov
      - name: Run the tests
        working-directory: python
        run: |
          ../bin/test_all.sh "*_test.py" "pytest *_test.py"
