name: Test Rust projects

on:
  push:
    paths:
      - rust/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker://rust:1.37.0
      - run: |
          cd rust
          ../bin/test_all.sh Cargo.toml 'cargo test'
        if: |
          contains(github.event.commits[0].message, '[skip ci]') == false &&
          contains(github.event.commits[0].message, '[ci skip]') == false
