name: Test Python projects

on:
  push:
    paths:
      - python/*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Test Python projects
        run: |
          cd python
          ../bin/test_all.sh *_test.py 'python3 *_test.py'
        if: |
          contains(github.event.commits[0].message, '[skip ci]') == false &&
          contains(github.event.commits[0].message, '[ci skip]') == false
